# Generated by Django 4.2.1 on 2023-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=15)),
                ('std_email', models.EmailField(max_length=30)),
                ('std_contact', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
